cypress-run:
  image: ubuntu:22.04
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - npm install -g pnpm
    - apt-get install -y xvfb
    - echo "STORE_PATH=$(pnpm store path --silent)" >> $CI_ENVIRONMENT_SLUG
    - pnpm install
    - pnpm build
    - xvfb-run pnpm cypress run
  cache:
    paths:
      - $STORE_PATH
    key: $CACHE_RESTORE_KEY
  environment:
    name: $CI_ENVIRONMENT_SLUG
    url: $CI_PROJECT_URL/-/environments/$CI_ENVIRONMENT_SLUG
